/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'n0216777' at '7/5/17 9:58 AM' with Gradle 2.14.1
 *
 * @author n0216777, @date 7/5/17 9:58 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
